import type { NextRequest } from 'next/server';

// Always fetch a fresh sitemap from the API (no Next.js cache),
// so that changes in SEO configuration are immediately visible.
export const dynamic = 'force-dynamic';

/**
 * Proxy sitemap from the API service so that
 * https://gigsafehub.com/sitemap.xml serves the dynamic sitemap
 * generated by the Express API at /sitemap.xml.
 */
export async function GET(_req: NextRequest) {
  const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';

  const response = await fetch(`${apiBaseUrl}/sitemap.xml`, {
    cache: 'no-store',
  });

  const body = await response.text();

  return new Response(body, {
    status: response.status,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      // Cache is controlled by the API; here we just avoid extra caching in Next.js
    },
  });
}



