import { FinancialProduct, Article, ProductCategory } from '@gigsafehub/types';

export const INITIAL_PRODUCTS: FinancialProduct[] = [
  {
    id: '1',
    name: 'GigBank Pro',
    category: ProductCategory.BANKING,
    rating: 4.8,
    reviewsCount: 1240,
    description: 'A mobile-first banking solution designed specifically for freelancers with automated tax savings buckets.',
    pros: ['No monthly fees', 'Automated tax withholding', 'Early direct deposit'],
    cons: ['No physical branches', 'Limited cash deposit network'],
    fees: '$0/mo',
    features: ['Tax Buckets', 'Invoicing Tool', 'Expense Tracking'],
    affiliateLink: 'https://gigbank.demo/signup',
    safetyScore: 98,
    logoUrl: 'https://picsum.photos/64/64?random=1'
  },
  {
    id: '2',
    name: 'SafeRide Insure',
    category: ProductCategory.INSURANCE,
    rating: 4.5,
    reviewsCount: 850,
    description: 'On-demand vehicle insurance for rideshare drivers. Pay only when the app is on.',
    pros: ['Pay-per-mile', 'Gap coverage included', 'Fast claims process'],
    cons: ['State availability limited', 'Higher deductible options'],
    fees: 'Base $20/mo + mileage',
    features: ['Rideshare Endorsement', 'Deductible Fund', '24/7 Support'],
    affiliateLink: 'https://saferide.demo/quote',
    safetyScore: 95,
    logoUrl: 'https://picsum.photos/64/64?random=2'
  },
  {
    id: '3',
    name: 'TurboTax Gig',
    category: ProductCategory.TAX_TOOLS,
    rating: 4.2,
    reviewsCount: 5600,
    description: 'Tax filing software optimized for Schedule C filers and independent contractors.',
    pros: ['Import expenses from bank', 'Audit defense', 'Live CPA help'],
    cons: ['Expensive for simple returns', 'Upsell heavy'],
    fees: '$89/state',
    features: ['Mileage Tracker', 'Expense Scanner', 'QBI Deduction Calculator'],
    affiliateLink: 'https://turbotax.demo/gig',
    safetyScore: 99,
    logoUrl: 'https://picsum.photos/64/64?random=3'
  },
  {
    id: '4',
    name: 'StashInvest',
    category: ProductCategory.INVESTMENT,
    rating: 4.0,
    reviewsCount: 320,
    description: 'Micro-investing for inconsistent income streams. Round up your purchases to buy fractional shares.',
    pros: ['Low barrier to entry', 'Educational content', 'Auto-stash feature'],
    cons: ['Monthly subscription fee', 'Limited trading window'],
    fees: '$3/mo',
    features: ['Fractional Shares', 'Retirement Accounts', 'Stock-Back Card'],
    affiliateLink: 'https://stash.demo/start',
    safetyScore: 92,
    logoUrl: 'https://picsum.photos/64/64?random=4'
  },
  {
    id: '5',
    name: 'Hiscox',
    category: ProductCategory.INSURANCE,
    rating: 4.6,
    reviewsCount: 3400,
    description: 'Specialized small business insurance with tailored policies for freelancers and consultants.',
    pros: ['Instant coverage', 'Tailored to specific professions', 'High policy limits'],
    cons: ['Can be pricier for low risk', 'Strict underwriting'],
    fees: 'From $30/mo',
    features: ['Professional Liability', 'General Liability', 'Cyber Security'],
    affiliateLink: 'https://hiscox.demo/quote',
    safetyScore: 97,
    logoUrl: 'https://picsum.photos/64/64?random=5'
  },
  {
    id: '6',
    name: 'Next Insurance',
    category: ProductCategory.INSURANCE,
    rating: 4.7,
    reviewsCount: 2900,
    description: '100% online insurance designed for speed and simplicity. Get a certificate of insurance in minutes.',
    pros: ['Fast mobile app', 'Bundling discounts', 'Live Certificates'],
    cons: ['Limited human agent access', 'Not all risks covered'],
    fees: 'From $25/mo',
    features: ['General Liability', 'Workers Comp', 'Tools & Equipment'],
    affiliateLink: 'https://next.demo/quote',
    safetyScore: 96,
    logoUrl: 'https://picsum.photos/64/64?random=6'
  }
];

export const INITIAL_ARTICLES: Article[] = [
  {
    id: '101',
    slug: 'hiscox-vs-next-insurance',
    title: 'Hiscox vs. Next Insurance: The Ultimate Showdown for Gig Workers',
    excerpt: 'Deciding between Hiscox and Next? We break down the coverage, costs, and claims process to help you pick the right shield.',
    partnerTag: 'Partner: Hiscox',
    date: 'Oct 12, 2024',
    imageUrl: 'https://picsum.photos/800/400?random=10',
    relatedProductIds: ['5', '6'],
    locale: 'en-US',
    content: `
      <p>As a gig worker, your liability is on the line every day. Whether you are a freelance consultant, a handyman, or a digital marketer, one lawsuit could wipe out your savings. That is why General Liability insurance is not just a nice-to-have; it is your shield.</p>

      <h3 class="text-xl font-bold mt-6 mb-3">Why You Need Liability Coverage</h3>
      <p>Clients are increasingly requiring proof of insurance before signing contracts. Both Hiscox and Next Insurance specialize in serving micro-businesses and sole proprietors, but they take different approaches.</p>
    `
  },
  {
    id: '102',
    slug: 'tax-write-offs-2024',
    title: 'Top 10 Tax Write-Offs Every Freelancer Misses',
    excerpt: 'Stop leaving money on the table. From home office deductions to software subscriptions, here is what you can claim this year.',
    partnerTag: 'Tax Tips',
    date: 'Nov 01, 2024',
    imageUrl: 'https://picsum.photos/800/400?random=11',
    locale: 'en-US',
    content: '<p>Content coming soon...</p>'
  },
  {
    id: '103',
    slug: 'banking-for-freelancers',
    title: 'Why You Should Never Mix Personal and Business Banking',
    excerpt: 'The "Corporate Veil" is real. Learn why separating your finances is the first step to protecting your personal assets.',
    partnerTag: 'GigBank',
    date: 'Sep 24, 2024',
    imageUrl: 'https://picsum.photos/800/400?random=12',
    locale: 'Both',
    content: '<p>Content coming soon...</p>'
  },
  {
    id: '104',
    slug: 'ipva-motoristas-app',
    title: 'IPVA para Motoristas de Aplicativo no Brasil: Guia 2024',
    excerpt: 'Entenda como funcionam as isenções e descontos de IPVA para motoristas Uber e 99 em diferentes estados brasileiros.',
    partnerTag: 'Impostos BR',
    date: 'Nov 05, 2024',
    imageUrl: 'https://picsum.photos/800/400?random=13',
    locale: 'pt-BR',
    content: '<p>O Imposto sobre a Propriedade de Veículos Automotores (IPVA) é uma das maiores despesas anuais para motoristas de aplicativo no Brasil. Neste guia, exploramos as regras de isenção no Rio de Janeiro, São Paulo e outros estados.</p>'
  }
];

export const MOCK_ADMIN_USER = {
  id: 'admin-1',
  email: 'admin@gigsafehub.com',
  name: 'Super Admin',
  role: 'admin' as const
};

export const TRANSLATIONS = {
  'en-US': {
    nav: {
      home: 'Home',
      insurance: 'Insurance',
      insuranceGeneral: 'General Liability',
      insuranceProfessional: 'Professional Liability',
      insuranceHealth: 'Health Insurance',
      insuranceVehicle: 'Vehicle Insurance',
      compare: 'Compare',
      guides: 'Guides',
      blog: 'Blog',
      about: 'About Us',
      getQuote: 'Get Quote',
      admin: 'Admin'
    },
    home: {
      title: 'Find Your Gig',
      titleHighlight: 'Insurance Shield',
      subtitle: 'Unbiased reviews, safety scores, and comparisons of banking, insurance, and tax tools designed for freelancers.',
      cta: 'Start My Free Quote',
      readGuides: 'Read Guides',
      topRated: 'Top Rated Gig Tools',
      curated: 'Curated selections with the highest safety scores.',
      viewAll: 'View All',
      latestArticles: 'Latest Articles & Insights'
    },
    articles: {
      title: 'Financial Guides & Insights',
      subtitle: 'Expert advice on managing risk, taxes, and income in the gig economy.',
      loading: 'Loading articles...',
      noArticles: 'No articles found for this region.',
      allArticles: 'All Articles',
      allArticlesSubtitle: 'Explore insights and guides about insurance for gig economy workers',
      filterBy: 'Filter by:',
      all: 'All',
      noArticlesFound: 'No articles found',
      noArticlesMessage: 'Try selecting a different category or check back later.',
      showing: 'Showing',
      article: 'article',
      articles: 'articles',
      in: 'in',
      readMore: 'Read More'
    },
    common: {
      loading: 'Loading...',
      minRead: 'min read',
      relatedProducts: 'Related Products',
      relatedProductsDescription: 'Check out these related insurance products',
      backToArticles: 'Back to Articles',
      backToComparisons: 'Back to Comparisons',
      articleCredits: 'Article created by {brand}. For republication, please maintain credits and link to {website}.',
      articleCreditsBrand: 'GigSafeHub',
      articleCreditsWebsite: 'gigsafehub.com',
      home: 'Home',
      products: 'Products',
      subcategories: 'Subcategories',
      browseCategories: 'Browse Categories',
      browseSubcategories: 'Browse Subcategories',
      noContentYet: 'No content yet',
      noContentMessage: "This category doesn't have any content yet. Check back soon!",
      goToHome: 'Go to Home',
      compareSelected: 'Compare Selected',
      youCanOnlyCompare: 'You can only compare up to 3 products.'
    },
    legal: {
      privacyTitle: 'Privacy Policy',
      termsTitle: 'Terms of Use',
      lastUpdated: 'Last Updated',
      effectiveDate: 'Effective Date',
      introduction: 'Introduction',
      informationWeCollect: 'Information We Collect',
      howWeUseInformation: 'How We Use Your Information',
      dataProtection: 'Data Protection',
      yourRights: 'Your Rights',
      cookies: 'Cookies',
      thirdPartyServices: 'Third-Party Services',
      changesToPolicy: 'Changes to This Policy',
      contactUs: 'Contact Us',
      acceptance: 'Acceptance of Terms',
      useOfService: 'Use of Service',
      userAccounts: 'User Accounts',
      intellectualProperty: 'Intellectual Property',
      disclaimer: 'Disclaimer',
      limitationOfLiability: 'Limitation of Liability',
      indemnification: 'Indemnification',
      governingLaw: 'Governing Law',
      changesToTerms: 'Changes to Terms'
    },
    tools: {
      title: 'Free Tools',
      subtitle: 'Calculators and tools to help you make smarter financial decisions',
      lossIncomeSimulator: {
        title: 'Loss Income Simulator',
        subtitle: 'Calculate how much you could lose without proper insurance coverage',
        description: 'Find out the real cost of being uninsured. Input your earnings and see how an accident or illness could impact your finances.',
        monthlyIncome: 'Monthly Income',
        monthlyIncomeHelp: 'Your average monthly earnings from gig work',
        workingDays: 'Working Days/Month',
        workingDaysHelp: 'Average days you work per month',
        profession: 'Profession',
        professionHelp: 'Select your main gig work type',
        recoveryTime: 'Recovery Time (Days)',
        recoveryTimeHelp: 'Estimated days unable to work',
        calculate: 'Calculate My Risk',
        calculating: 'Calculating...',
        results: 'Your Risk Analysis',
        potentialLoss: 'Potential Income Loss',
        dailyRate: 'Daily Rate',
        riskLevel: 'Risk Level',
        riskLow: 'Low Risk',
        riskMedium: 'Medium Risk',
        riskHigh: 'High Risk',
        riskCritical: 'Critical Risk',
        recommendation: 'Our Recommendation',
        recommendationText: 'Based on your profile, we recommend getting insurance coverage to protect your income. A small monthly investment can save you from devastating financial losses.',
        startOver: 'Calculate Again',
        compareInsurance: 'Compare Insurance Options',
        professions: {
          rideshare: 'Rideshare Driver (Uber, Lyft)',
          delivery: 'Delivery Worker (DoorDash, Instacart)',
          freelancer: 'Freelancer/Consultant',
          handyman: 'Handyman/Contractor',
          photographer: 'Photographer/Videographer',
          other: 'Other Gig Worker'
        },
        scenarios: {
          title: 'Common Scenarios',
          accident: 'Car Accident',
          accidentDays: '30-90 days recovery',
          illness: 'Serious Illness',
          illnessDays: '14-60 days recovery',
          injury: 'Work Injury',
          injuryDays: '7-30 days recovery'
        },
        disclaimer: 'This calculator provides estimates only. Actual losses may vary based on your specific situation. Consult with an insurance professional for personalized advice.'
      },
      dailyProfitCalculator: {
        title: 'Daily Real Profit Calculator',
        subtitle: 'Discover your true earnings after deducting all expenses',
        description: 'Most gig workers only see gross revenue. Find out how much you actually earn per hour after fuel, maintenance, taxes, and other costs.',
        grossRevenue: 'Gross Daily Revenue',
        grossRevenueHelp: 'Total amount you earned today (before expenses)',
        hoursWorked: 'Hours Worked',
        hoursWorkedHelp: 'Total hours you worked (including waiting time)',
        fuelCost: 'Fuel Cost',
        fuelCostHelp: 'Amount spent on gas/charging today',
        maintenanceCost: 'Maintenance/Depreciation',
        maintenanceCostHelp: 'Estimated daily vehicle wear (tires, oil, repairs)',
        platformFee: 'Platform Fees',
        platformFeeHelp: 'Commissions taken by apps (Uber, iFood, etc.)',
        otherCosts: 'Other Costs',
        otherCostsHelp: 'Food, parking, tolls, etc.',
        calculate: 'Calculate Real Profit',
        calculating: 'Calculating...',
        results: 'Your Real Numbers',
        realDailyProfit: 'Real Daily Profit',
        realHourlyRate: 'Real Hourly Rate',
        profitMargin: 'Profit Margin',
        expenseBreakdown: 'Expense Breakdown',
        comparison: 'Comparison',
        minimumWage: 'vs Minimum Wage',
        targetHourly: 'vs Target ($25/hr)',
        insights: {
          title: 'Insights',
          good: 'Your earnings are healthy! Keep tracking to maintain consistency.',
          average: 'Your earnings are around average. Look for ways to reduce costs or increase efficiency.',
          low: 'Your real profit is below expectations. Consider reviewing your expenses or exploring better earning hours.',
          critical: 'Warning: Your costs are eating into your profits significantly. Time to reassess your strategy.'
        },
        tips: {
          title: 'Tips to Increase Profit',
          tip1: 'Track peak hours and work during high-demand periods',
          tip2: 'Reduce idle time between rides/deliveries',
          tip3: 'Consider fuel-efficient routes',
          tip4: 'Maintain your vehicle regularly to avoid costly repairs'
        },
        disclaimer: 'This calculator provides estimates based on your inputs. Actual profits may vary. Consider tracking your expenses daily for more accurate results.'
      },
      monthlyGoalSimulator: {
        title: 'Monthly Goal Simulator',
        subtitle: 'Plan how to reach your income goals',
        description: 'Set your monthly income target and discover exactly how many hours, days, and trips you need to reach it.',
        monthlyGoal: 'Monthly Income Goal',
        monthlyGoalHelp: 'How much do you want to earn this month?',
        averagePerTrip: 'Average per Trip/Delivery',
        averagePerTripHelp: 'Your average earnings per ride or delivery',
        hoursPerDay: 'Hours per Day',
        hoursPerDayHelp: 'How many hours can you work daily?',
        daysPerWeek: 'Days per Week',
        daysPerWeekHelp: 'How many days do you want to work?',
        currentEarnings: 'Current Month Earnings',
        currentEarningsHelp: 'How much have you earned so far this month?',
        calculate: 'Calculate My Plan',
        calculating: 'Calculating...',
        results: 'Your Action Plan',
        tripsNeeded: 'Trips/Deliveries Needed',
        hoursNeeded: 'Hours Needed',
        daysNeeded: 'Days Needed',
        dailyTarget: 'Daily Target',
        weeklyTarget: 'Weekly Target',
        remaining: 'Remaining to Goal',
        progress: 'Current Progress',
        onTrack: 'You\'re on track!',
        behindSchedule: 'You\'re behind schedule',
        aheadSchedule: 'You\'re ahead of schedule!',
        insights: {
          title: 'Insights',
          achievable: 'Your goal is achievable with your current pace. Stay consistent!',
          challenging: 'This goal is challenging. Consider increasing hours or finding higher-paying opportunities.',
          aggressive: 'This is an aggressive goal. You may need to optimize your strategy significantly.',
          easy: 'You can easily exceed this goal! Consider setting a higher target.'
        },
        tips: {
          title: 'Tips to Reach Your Goal',
          tip1: 'Focus on peak demand hours for higher earnings',
          tip2: 'Track your daily progress to stay motivated',
          tip3: 'Set weekly milestones to stay on track',
          tip4: 'Consider multi-apping during slow periods'
        },
        disclaimer: 'This simulator provides estimates based on averages. Actual results depend on demand, location, and other factors.'
      },
      hiddenCostsCalculator: {
        title: 'Hidden Costs Calculator',
        subtitle: 'Discover costs you might be overlooking',
        description: 'Most gig workers forget about depreciation, insurance, phone bills, and other hidden costs. Find out your true operating expenses.',
        vehicleValue: 'Vehicle Value',
        vehicleValueHelp: 'Current market value of your vehicle',
        vehicleAge: 'Vehicle Age (Years)',
        vehicleAgeHelp: 'How old is your vehicle?',
        monthlyMiles: 'Monthly Miles/KM',
        monthlyMilesHelp: 'Average distance driven per month for work',
        phoneAndData: 'Phone & Data Plan',
        phoneAndDataHelp: 'Monthly cost of your phone plan',
        carInsurance: 'Car Insurance',
        carInsuranceHelp: 'Monthly vehicle insurance cost',
        healthInsurance: 'Health Insurance',
        healthInsuranceHelp: 'Monthly health insurance (if any)',
        emergencyFund: 'Emergency Fund Contribution',
        emergencyFundHelp: 'Monthly savings for emergencies',
        calculate: 'Calculate Hidden Costs',
        calculating: 'Analyzing...',
        results: 'Your Hidden Costs',
        totalMonthlyCosts: 'Total Monthly Hidden Costs',
        dailyCosts: 'Daily Hidden Costs',
        costPerMile: 'Cost per Mile/KM',
        depreciation: 'Vehicle Depreciation',
        depreciationHelp: 'Estimated monthly loss in vehicle value',
        tireWear: 'Tire Wear',
        oilChanges: 'Oil & Fluids',
        brakes: 'Brake Wear',
        breakdown: 'Cost Breakdown',
        category: {
          vehicle: 'Vehicle Costs',
          insurance: 'Insurance & Protection',
          technology: 'Technology',
          savings: 'Savings & Emergency'
        },
        insights: {
          title: 'What This Means',
          high: 'Your hidden costs are significant. Make sure to factor these into your earnings calculations.',
          medium: 'Your hidden costs are average. There may be room to optimize some expenses.',
          low: 'Your hidden costs are well managed. Keep tracking to maintain control.'
        },
        tips: {
          title: 'Ways to Reduce Hidden Costs',
          tip1: 'Consider a more fuel-efficient vehicle',
          tip2: 'Shop around for better insurance rates annually',
          tip3: 'Do basic maintenance yourself when possible',
          tip4: 'Track all expenses for tax deductions'
        },
        disclaimer: 'Estimates are based on industry averages and your inputs. Actual costs may vary based on your specific situation and location.'
      }
    }
  },
  'pt-BR': {
    nav: {
      home: 'Início',
      insurance: 'Seguros',
      insuranceGeneral: 'Responsabilidade Civil',
      insuranceProfessional: 'Responsabilidade Profissional',
      insuranceHealth: 'Seguro Saúde',
      insuranceVehicle: 'Seguro Veículo',
      compare: 'Comparador',
      guides: 'Guias',
      blog: 'Blog',
      about: 'Sobre Nós',
      getQuote: 'Cotação',
      admin: 'Admin',
      faq: 'FAQ'
    },
    home: {
      title: 'Encontre sua',
      titleHighlight: 'Proteção Ideal',
      subtitle: 'Análises imparciais, pontuações de segurança e comparações de ferramentas bancárias e seguros para autônomos e freelancers.',
      cta: 'Iniciar Cotação Grátis',
      readGuides: 'Ler Guias',
      topRated: 'Ferramentas Mais Bem Avaliadas',
      curated: 'Seleções curadas com as maiores pontuações de segurança.',
      viewAll: 'Ver Todas',
      latestArticles: 'Últimos Artigos e Insights'
    },
    articles: {
      title: 'Guias Financeiros e Insights',
      subtitle: 'Conselhos de especialistas sobre gestão de riscos, impostos e renda para autônomos.',
      loading: 'Carregando artigos...',
      noArticles: 'Nenhum artigo encontrado para esta região.',
      allArticles: 'Todos os Artigos',
      allArticlesSubtitle: 'Explore insights e guias sobre seguros para autônomos e trabalhadores de aplicativo',
      filterBy: 'Filtrar por:',
      all: 'Todos',
      noArticlesFound: 'Nenhum artigo encontrado',
      noArticlesMessage: 'Tente selecionar uma categoria diferente ou volte mais tarde.',
      showing: 'Mostrando',
      article: 'artigo',
      articles: 'artigos',
      in: 'em',
      readMore: 'Ler mais'
    },
    common: {
      loading: 'Carregando...',
      minRead: 'min de leitura',
      relatedProducts: 'Produtos Relacionados',
      relatedProductsDescription: 'Confira estes produtos de seguro relacionados',
      backToArticles: 'Voltar aos Artigos',
      backToComparisons: 'Voltar aos Comparadores',
      articleCredits: 'Artigo criado por {brand}. Para republicação, favor manter créditos e link para {website}.',
      articleCreditsBrand: 'GigSafeHub',
      articleCreditsWebsite: 'gigsafehub.com',
      home: 'Início',
      products: 'Produtos',
      subcategories: 'Subcategorias',
      browseCategories: 'Navegar Categorias',
      browseSubcategories: 'Navegar Subcategorias',
      noContentYet: 'Ainda sem conteúdo',
      noContentMessage: 'Esta categoria ainda não tem conteúdo. Volte em breve!',
      goToHome: 'Ir para Início',
      compareSelected: 'Comparar Selecionados',
      youCanOnlyCompare: 'Você só pode comparar até 3 produtos.'
    },
    legal: {
      privacyTitle: 'Política de Privacidade',
      termsTitle: 'Termos de Uso',
      lastUpdated: 'Última Atualização',
      effectiveDate: 'Data de Vigência',
      introduction: 'Introdução',
      informationWeCollect: 'Informações que Coletamos',
      howWeUseInformation: 'Como Usamos Suas Informações',
      dataProtection: 'Proteção de Dados',
      yourRights: 'Seus Direitos',
      cookies: 'Cookies',
      thirdPartyServices: 'Serviços de Terceiros',
      changesToPolicy: 'Alterações nesta Política',
      contactUs: 'Entre em Contato',
      acceptance: 'Aceitação dos Termos',
      useOfService: 'Uso do Serviço',
      userAccounts: 'Contas de Usuário',
      intellectualProperty: 'Propriedade Intelectual',
      disclaimer: 'Aviso Legal',
      limitationOfLiability: 'Limitação de Responsabilidade',
      indemnification: 'Indenização',
      governingLaw: 'Lei Aplicável',
      changesToTerms: 'Alterações nos Termos'
    },
    tools: {
      title: 'Ferramentas Gratuitas',
      subtitle: 'Calculadoras e ferramentas para ajudar você a tomar decisões financeiras mais inteligentes',
      lossIncomeSimulator: {
        title: 'Simulador de Perda de Renda',
        subtitle: 'Calcule quanto você poderia perder sem uma cobertura de seguro adequada',
        description: 'Descubra o custo real de ficar sem seguro. Insira seus ganhos e veja como um acidente ou doença pode impactar suas finanças.',
        monthlyIncome: 'Renda Mensal',
        monthlyIncomeHelp: 'Sua média de ganhos mensais como autônomo',
        workingDays: 'Dias Trabalhados/Mês',
        workingDaysHelp: 'Média de dias que você trabalha por mês',
        profession: 'Profissão',
        professionHelp: 'Selecione seu principal tipo de trabalho',
        recoveryTime: 'Tempo de Recuperação (Dias)',
        recoveryTimeHelp: 'Dias estimados sem poder trabalhar',
        calculate: 'Calcular Meu Risco',
        calculating: 'Calculando...',
        results: 'Sua Análise de Risco',
        potentialLoss: 'Perda Potencial de Renda',
        dailyRate: 'Diária',
        riskLevel: 'Nível de Risco',
        riskLow: 'Risco Baixo',
        riskMedium: 'Risco Médio',
        riskHigh: 'Risco Alto',
        riskCritical: 'Risco Crítico',
        recommendation: 'Nossa Recomendação',
        recommendationText: 'Com base no seu perfil, recomendamos obter uma cobertura de seguro para proteger sua renda. Um pequeno investimento mensal pode te salvar de perdas financeiras devastadoras.',
        startOver: 'Calcular Novamente',
        compareInsurance: 'Comparar Opções de Seguro',
        professions: {
          rideshare: 'Motorista de Aplicativo (Uber, 99)',
          delivery: 'Entregador (iFood, Rappi)',
          freelancer: 'Freelancer/Consultor',
          handyman: 'Prestador de Serviços',
          photographer: 'Fotógrafo/Videomaker',
          other: 'Outro Autônomo'
        },
        scenarios: {
          title: 'Cenários Comuns',
          accident: 'Acidente de Carro',
          accidentDays: '30-90 dias de recuperação',
          illness: 'Doença Grave',
          illnessDays: '14-60 dias de recuperação',
          injury: 'Lesão no Trabalho',
          injuryDays: '7-30 dias de recuperação'
        },
        disclaimer: 'Esta calculadora fornece apenas estimativas. Perdas reais podem variar com base na sua situação específica. Consulte um profissional de seguros para orientação personalizada.'
      },
      dailyProfitCalculator: {
        title: 'Calculadora de Lucro Real Diário',
        subtitle: 'Descubra seus ganhos reais após deduzir todas as despesas',
        description: 'A maioria dos autônomos só vê a receita bruta. Descubra quanto você realmente ganha por hora após combustível, manutenção, impostos e outros custos.',
        grossRevenue: 'Receita Bruta Diária',
        grossRevenueHelp: 'Valor total que você ganhou hoje (antes das despesas)',
        hoursWorked: 'Horas Trabalhadas',
        hoursWorkedHelp: 'Total de horas trabalhadas (incluindo tempo de espera)',
        fuelCost: 'Custo de Combustível',
        fuelCostHelp: 'Valor gasto com gasolina/recarga hoje',
        maintenanceCost: 'Manutenção/Depreciação',
        maintenanceCostHelp: 'Desgaste diário estimado do veículo (pneus, óleo, reparos)',
        platformFee: 'Taxas das Plataformas',
        platformFeeHelp: 'Comissões cobradas pelos apps (Uber, iFood, etc.)',
        otherCosts: 'Outros Custos',
        otherCostsHelp: 'Alimentação, estacionamento, pedágios, etc.',
        calculate: 'Calcular Lucro Real',
        calculating: 'Calculando...',
        results: 'Seus Números Reais',
        realDailyProfit: 'Lucro Real Diário',
        realHourlyRate: 'Ganho Real por Hora',
        profitMargin: 'Margem de Lucro',
        expenseBreakdown: 'Detalhamento de Despesas',
        comparison: 'Comparação',
        minimumWage: 'vs Salário Mínimo',
        targetHourly: 'vs Meta (R$30/hr)',
        insights: {
          title: 'Análise',
          good: 'Seus ganhos estão saudáveis! Continue acompanhando para manter a consistência.',
          average: 'Seus ganhos estão na média. Procure formas de reduzir custos ou aumentar a eficiência.',
          low: 'Seu lucro real está abaixo do esperado. Considere revisar suas despesas ou explorar horários de maior ganho.',
          critical: 'Atenção: Seus custos estão consumindo seus lucros significativamente. Hora de reavaliar sua estratégia.'
        },
        tips: {
          title: 'Dicas para Aumentar o Lucro',
          tip1: 'Acompanhe os horários de pico e trabalhe durante períodos de alta demanda',
          tip2: 'Reduza o tempo ocioso entre corridas/entregas',
          tip3: 'Considere rotas mais econômicas',
          tip4: 'Faça manutenção regular do veículo para evitar reparos caros'
        },
        disclaimer: 'Esta calculadora fornece estimativas baseadas nas suas entradas. Os lucros reais podem variar. Considere acompanhar suas despesas diariamente para resultados mais precisos.'
      },
      monthlyGoalSimulator: {
        title: 'Simulador de Meta Mensal',
        subtitle: 'Planeje como alcançar suas metas de renda',
        description: 'Defina sua meta de renda mensal e descubra exatamente quantas horas, dias e corridas você precisa para alcançá-la.',
        monthlyGoal: 'Meta de Renda Mensal',
        monthlyGoalHelp: 'Quanto você quer ganhar este mês?',
        averagePerTrip: 'Média por Corrida/Entrega',
        averagePerTripHelp: 'Seu ganho médio por corrida ou entrega',
        hoursPerDay: 'Horas por Dia',
        hoursPerDayHelp: 'Quantas horas você pode trabalhar por dia?',
        daysPerWeek: 'Dias por Semana',
        daysPerWeekHelp: 'Quantos dias você quer trabalhar?',
        currentEarnings: 'Ganhos do Mês Atual',
        currentEarningsHelp: 'Quanto você já ganhou este mês?',
        calculate: 'Calcular Meu Plano',
        calculating: 'Calculando...',
        results: 'Seu Plano de Ação',
        tripsNeeded: 'Corridas/Entregas Necessárias',
        hoursNeeded: 'Horas Necessárias',
        daysNeeded: 'Dias Necessários',
        dailyTarget: 'Meta Diária',
        weeklyTarget: 'Meta Semanal',
        remaining: 'Falta para a Meta',
        progress: 'Progresso Atual',
        onTrack: 'Você está no caminho certo!',
        behindSchedule: 'Você está atrasado',
        aheadSchedule: 'Você está adiantado!',
        insights: {
          title: 'Análise',
          achievable: 'Sua meta é alcançável com seu ritmo atual. Continue consistente!',
          challenging: 'Essa meta é desafiadora. Considere aumentar as horas ou buscar oportunidades de maior ganho.',
          aggressive: 'Essa é uma meta agressiva. Você pode precisar otimizar sua estratégia significativamente.',
          easy: 'Você pode facilmente superar essa meta! Considere definir uma meta maior.'
        },
        tips: {
          title: 'Dicas para Alcançar sua Meta',
          tip1: 'Foque nos horários de pico para ganhos maiores',
          tip2: 'Acompanhe seu progresso diário para manter a motivação',
          tip3: 'Defina marcos semanais para se manter no caminho',
          tip4: 'Considere usar múltiplos apps em períodos de baixa demanda'
        },
        disclaimer: 'Este simulador fornece estimativas baseadas em médias. Os resultados reais dependem da demanda, localização e outros fatores.'
      },
      hiddenCostsCalculator: {
        title: 'Calculadora de Custos Invisíveis',
        subtitle: 'Descubra custos que você pode estar ignorando',
        description: 'A maioria dos autônomos esquece da depreciação, seguro, conta de celular e outros custos ocultos. Descubra suas verdadeiras despesas operacionais.',
        vehicleValue: 'Valor do Veículo',
        vehicleValueHelp: 'Valor de mercado atual do seu veículo',
        vehicleAge: 'Idade do Veículo (Anos)',
        vehicleAgeHelp: 'Quantos anos tem seu veículo?',
        monthlyMiles: 'KM Mensal',
        monthlyMilesHelp: 'Distância média percorrida por mês para trabalho',
        phoneAndData: 'Celular e Internet',
        phoneAndDataHelp: 'Custo mensal do plano de celular',
        carInsurance: 'Seguro do Veículo',
        carInsuranceHelp: 'Custo mensal do seguro do veículo',
        healthInsurance: 'Plano de Saúde',
        healthInsuranceHelp: 'Plano de saúde mensal (se houver)',
        emergencyFund: 'Reserva de Emergência',
        emergencyFundHelp: 'Economia mensal para emergências',
        calculate: 'Calcular Custos Ocultos',
        calculating: 'Analisando...',
        results: 'Seus Custos Invisíveis',
        totalMonthlyCosts: 'Total de Custos Mensais Ocultos',
        dailyCosts: 'Custos Diários Ocultos',
        costPerMile: 'Custo por KM',
        depreciation: 'Depreciação do Veículo',
        depreciationHelp: 'Perda mensal estimada no valor do veículo',
        tireWear: 'Desgaste de Pneus',
        oilChanges: 'Óleo e Fluidos',
        brakes: 'Desgaste de Freios',
        breakdown: 'Detalhamento de Custos',
        category: {
          vehicle: 'Custos do Veículo',
          insurance: 'Seguros e Proteção',
          technology: 'Tecnologia',
          savings: 'Poupança e Emergência'
        },
        insights: {
          title: 'O Que Isso Significa',
          high: 'Seus custos ocultos são significativos. Certifique-se de incluí-los nos cálculos de ganhos.',
          medium: 'Seus custos ocultos estão na média. Pode haver espaço para otimizar algumas despesas.',
          low: 'Seus custos ocultos estão bem controlados. Continue acompanhando para manter o controle.'
        },
        tips: {
          title: 'Formas de Reduzir Custos Ocultos',
          tip1: 'Considere um veículo mais econômico',
          tip2: 'Pesquise melhores taxas de seguro anualmente',
          tip3: 'Faça manutenções básicas você mesmo quando possível',
          tip4: 'Registre todas as despesas para deduções fiscais'
        },
        disclaimer: 'As estimativas são baseadas em médias do setor e nas suas entradas. Os custos reais podem variar conforme sua situação específica e localização.'
      }
    }
  }
};

